### ISSUE TITLE
Hero transition very strange

### ISSUE THREAD

**Issue by mrleesin** [Idean/Flutter-Neumorphic#102]
In moment of animation from one Neumorphic to another there are strange effects like no text style

**Comment by florent37** [comment]
can you send us a video & a sample code please ?

**Comment by florent37** [comment]
for a video, register it and drag/drop the file in this issue

**Comment by mrleesin** [comment]
[RPReplay_Final1588495339.mov.zip](https://github.com/Idean/Flutter-Neumorphic/files/4569849/RPReplay_Final1588495339.mov.zip)

**Comment by florent37** [comment]
you mean thi yellow line ?

<img width="422" alt="Capture d’écran 2020-05-03 à 12 55 02" src="https://user-images.githubusercontent.com/5754972/80912463-5661e880-8d3d-11ea-8d43-92426f880e54.png">

**Comment by florent37** [comment]
it happen when a Text try to find a material theme, I will try to find why !

**Comment by mrleesin** [comment]
> you mean thi yellow line ?
> 
> <img alt="Capture d’écran 2020-05-03 à 12 55 02" width="422" src="https://user-images.githubusercontent.com/5754972/80912463-5661e880-8d3d-11ea-8d43-92426f880e54.png">

yes!
how to fix it?

**Comment by mrleesin** [comment]
> it happen when a Text try to find a material theme, I will try to find why !

thank you in advance!!

**Comment by florent37** [comment]
I'll need to try

a simple fix you can try : handle your text by a "material" element, with no-effect, like : 

```
Neumorphic(
   chld: Material(
         elevation: 0,
          child: Text(
```

**Comment by mrleesin** [comment]
That fixed it! ) Thank you
also have to assign background color

**Comment by florent37** [comment]
I don't know if it's related to neumorphic or hero. I think it's because the widget is detached from the tree and cannot find the theme when the hero animation happen.

I'll try to reproduce this with and without neumorphic tomorrow, and see if I need to add some code to fix it

**Comment by florent37** [comment]
I added an `AnimatedDefaultTextStyle` inside Neumorphic container (like the material element)

can you try the `1.0.8+1` ? 

without the Material added widget ?

before : 

```dart
Neumorphic(
   chld: Material(
         elevation: 0,
          child: Text(
```

after 
```dart
Neumorphic(
   chld: Text(
```

**Comment by mrleesin** [comment]
its working fine!

**Comment by florent37** [comment]
thanks for your issue !
