### ISSUE TITLE
NeumorphicToggleStyle doesn't have color property

### ISSUE THREAD

**Issue by Guidogl** [Idean/Flutter-Neumorphic#103]
Hi,

Very nice library but I am unable to change NeumorphicToggle background color. I think it should be added to NeumorphicToggleStyle

**Comment by florent37** [comment]
thanks for your issue 

I just added it and published it in 1.0.8

```dart
NeumorphicToggle(
              height: 50,
              style: NeumorphicToggleStyle(
                backgroundColor: Colors.red,
              ),
              ...
```

can you try ?
