### ISSUE TITLE
1.0.8+1 won't compile on Flutter stable (but downgrading to 1.0.8 works)

### ISSUE THREAD

**Issue by Coteh** [Idean/Flutter-Neumorphic#109]
Just installed 1.0.8+1, replaced a button in my app with `NeumorphicButton` and attempted to run on iOS simulator, I get the following:

```
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...

Compiler message:
../../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_neumorphic-1.0.8+1/lib/src/widget/container.dart:125:69: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../dev/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
      style: this.textStyle ?? material.Theme.of(context).textTheme.bodyText2,
                                                                    ^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
Failed to build bundle.
Error launching application on iPhone 11 Pro Max.
Exited (sigterm)
```

It seems like this is happening because [an update to `TextTheme` to match the Material 2018 APIs](https://github.com/flutter/flutter/pull/48547) is not in Flutter stable yet. I downgraded to 1.0.8 for now, but perhaps a notice can be added that once Flutter stable catches up to their master channel it'll eventually work. I'm not sure what the best option is here, but thought I'd bring this up in case anyone else is running into the same issue.

**Comment by riskiadi** [comment]
me too, getting this error
`The getter 'bodyText2' isn't defined for the class 'TextTheme'.`

**Comment by florent37** [comment]
yes, it's my fault, I pushes a fix in 1.0.8+3

thanks for your link, I set to `body2` for now, and in a near future it'll become `bodyText2`

**Comment by florent37** [comment]
can you try the 1.0.8+3 ?

**Comment by florent37** [comment]
another solution was to force the flutter min sdk :D
