### ISSUE TITLE
Edit text inputs like in this image

### ISSUE THREAD

**Issue by nilsi** [Idean/Flutter-Neumorphic#112]
Hi! Thank you for this awesome library!

How can I achieve a form like the image below? Especially the text inputs are what I wonder about. Is there a widget for it or any examples? 

Or it's just a concave shape that I then have to add an input inside? 

https://raw.githubusercontent.com/Idean/Flutter-Neumorphic/master/medias/samples/sample_form.png

![Image of edit text input](https://raw.githubusercontent.com/Idean/Flutter-Neumorphic/master/medias/samples/sample_form.png)

**Comment by nilsi** [comment]
Found the example here:

https://github.com/Idean/Flutter-Neumorphic/blob/master/example/lib/samples/form_sample.dart

**Comment by florent37** [comment]
Yes :) and it's juste a emboss stadium shape with an edit inside !
