### ISSUE TITLE
Undefined name '_selectedIndex' while adding toggle widget

### ISSUE THREAD

**Issue by Guidogl** [Idean/Flutter-Neumorphic#113]
Hello,

Can you explain more in-depth how to implement Toggle widget as I am trying to copy your example code and I am getting few errors?

`selectedIndex: _selectedIndex,` gives me an error - error: Undefined name '_selectedIndex'

`onChanged: (value) {
              setState(() {
                _selectedIndex = value;
                print('_firstSelected: 1');
              });
            },`

This piece of code gives me two errors: 

1) error: The method 'setState' isn't defined for the class 'GalleriesBar'. (undefined_method at [lt] lib\main.dart:111)
2) error: Undefined name '_selectedIndex'. (undefined_identifier at [lt] lib\main.dart:112)

**Comment by florent37** [comment]
Are you in a statefull widget, with a private variable _selectedIndex ?

Can you share your class/code ?

**Comment by florent37** [comment]
You have to store the current selected index in your statefull's state, like if you're using a checkbox, this widget does not store it configuration, you have to give it each time(frame). It's how flutter widgets works ;)

**Comment by Guidogl** [comment]
Okay, so I changed my class to statefull and added `int _selectedIndex = 0;` and now it works.

Sorry, for interruption, I am new to Flutter.

**Comment by florent37** [comment]
no worry, keep learn flutter, it's not easy the first weeks, but you'll see it's awesome :)
