### ISSUE TITLE
[Web] Circle not closed properly

### ISSUE THREAD

**Issue by bounty1342** [Idean/Flutter-Neumorphic#117]
You can see the end result there :

<img width="315" alt="Screenshot 2020-05-19 at 19 35 33" src="https://user-images.githubusercontent.com/6307253/82360437-ab724f80-9a09-11ea-90e2-76a98614a6c5.png">

Regards

**Comment by Debilobob** [comment]
Hello !

First, thank you for using our library :)

We know this issue.

We use the same code to render path between all platforms and it's affect just the Web version.

Actually web is in beta so we hope this will be corrected by flutter team directly ¯\_(ツ)_/¯

Emboss rendering is also affected in Web :(

**Comment by florent37** [comment]
we will wait for the stable version of flutter web then we will reopen it if it's not fixed :)
