### ISSUE TITLE
Neumorphic button tooltip

### ISSUE THREAD

**Issue by jaumard** [Idean/Flutter-Neumorphic#125]
Might nice to have for accessibility 

`tooltip: 'my tooltip'`

**Comment by florent37** [comment]
Thanks, just added this as optional on NeumorphicButton on 2.2.2

**Comment by jaumard** [comment]
Shit I have to remove it lol I did it on my fork too

**Comment by florent37** [comment]
:D sorry you should tell me this here

**Comment by jaumard** [comment]
No problem thanks for doing it ^^ removed on my side :) it was not a big change so it's fine lol
