### ISSUE TITLE
Bump kind of button 

### ISSUE THREAD

**Issue by rashmisridar** [Idean/Flutter-Neumorphic#129]
How to achieve circular background bump inside the shadow. Please check the below link for the requirement.

![tesla1](https://user-images.githubusercontent.com/8536749/83101500-15f15280-a0d0-11ea-83a5-65a2ee724d97.jpg)

**Comment by florent37** [comment]
That's a sample I included into the example project, check the ''tesla sample'' & you'll find the code

**Comment by florent37** [comment]
https://github.com/Idean/Flutter-Neumorphic/blob/master/example/lib/samples/testla_sample.dart

**Comment by florent37** [comment]
& play with a low intensity for the ''external button'' to have this blur effect

**Comment by rashmisridar** [comment]
Sure will check Thank you

**Comment by rashmisridar** [comment]
Taken your tesla sample code itself, made the following changes for the settings button but not able to get the exact affect . Please let me know where I need to work around.

`Align(
          alignment: Alignment.centerRight,
          child: Padding(
            padding: EdgeInsets.symmetric(horizontal: 12, vertical: 24),
            child: Neumorphic(
              drawSurfaceAboveChild: false,
              padding: EdgeInsets.all(10),
              boxShape: NeumorphicBoxShape.circle(),
              style: NeumorphicStyle(
                surfaceIntensity: 0.5,
                //lightSource: LightSource.topLeft,
                color: Color(0xFF111111),
                depth:20,
                intensity: 0.0,
                shape: NeumorphicShape.convex,
              ),
              child: Padding(
                padding: const EdgeInsets.all(2.0),
                child: Icon(
                  Icons.settings,
                  color: Colors.grey,
                ),
              ),
            ),
          ),
        )`

**Comment by bounty1342** [comment]
@rashmisridar : you need both the NeumorphicButton and NeumorphicContainer to achieve the desired effet.

**Comment by florent37** [comment]
Can you send a screenshoot of your button please ?

**Comment by florent37** [comment]
Your neumorphic container should have 15 depth I think, 0.3 intensity

And your button (child) should be convex, and have a margin of 1 or 2, with some little deph like 5

**Comment by rashmisridar** [comment]
![abc](https://user-images.githubusercontent.com/8536749/83233947-20cde500-a1ad-11ea-9d94-98843ad30e97.jpg)


```
Neumorphic(
              boxShape: NeumorphicBoxShape.circle(),
              style: NeumorphicStyle(shape: NeumorphicShape.convex,
                  intensity: 0.3,
                  shadowLightColor: Color(0xFF252A2E),
                  surfaceIntensity: 0.5,
                  depth: 15,
                  color: Colors.transparent),
              child: NeumorphicButton(
                margin: EdgeInsets.all(2),
                onClick: () {
                  NeumorphicTheme.of(context).usedTheme =
                  NeumorphicTheme.isUsingDark(context)
                      ? UsedTheme.DARK
                      : UsedTheme.DARK;

                },
                style: NeumorphicStyle(shape: NeumorphicShape.convex,
                    depth: 100,
                    //   disableDepth: true,
                    lightSource: LightSource.topRight,
                    intensity: 0.4,
                  color: Colors.black
                  ),
                boxShape: NeumorphicBoxShape.circle(),
                padding: const EdgeInsets.all(18.0),
                child: Icon(
                Icons.settings,
                color: Colors.grey,
                      )))
```

**Comment by bounty1342** [comment]
Using material color (transparent and black) is not appropriate for neumorphism has those can't cast their shadows to create the effect.

The intensity, is either an alpha pourcentage on the black or white color, but most implementations used lerp between colors. That why with full black you got a 0 intensity and zero effect.

Hope it help.

**Comment by florent37** [comment]
I succeed to reproduce with this code : 

```
Widget _bumpButton(Widget child) {
    return Neumorphic(
      drawSurfaceAboveChild: false,
      boxShape: NeumorphicBoxShape.circle(),
      style: NeumorphicStyle(
        color: Color(0xFF2D3238),
        depth: 8,
        intensity: 0.3,
        shape: NeumorphicShape.concave,
      ),
      child: NeumorphicButton(
          onPressed: () {},
          margin: EdgeInsets.all(3),
          padding: EdgeInsets.all(14.0),
          boxShape: NeumorphicBoxShape.circle(),
          style: NeumorphicStyle(
            color: Color(0xFF212528),
            depth: 0,
            shape: NeumorphicShape.convex,
          ),
          child: child),
    );
  }
```

and when I call : 

```
Align(
          alignment: Alignment.centerRight,
          child: Padding(
            padding: EdgeInsets.symmetric(horizontal: 16, vertical: 24),
            child: _bumpButton(
              Icon(
                Icons.settings,
                color: Colors.grey,
              ),
            ),
          ),
        )
```

**Comment by florent37** [comment]
look the render 

<img width="482" alt="Capture d’écran 2020-05-29 à 10 59 10" src="https://user-images.githubusercontent.com/5754972/83241712-887b3480-a19b-11ea-86d1-0623f74e9e11.png">

**Comment by florent37** [comment]
reopen if this implementation does not work :) but I find it really near from the png

**Comment by rashmisridar** [comment]
@florent37 Cool it's working ... Thank you
