### ISSUE TITLE
Need more explantation on readme

### ISSUE THREAD

**Issue by jaumard** [Idean/Flutter-Neumorphic#130]
I'm checking the NeumorphicThemeData and I'm kind of lost because I have no idea what those field will change.

For example accentColor and variantColor, I guess accent is the equivalent of material primary color. And variant for accent color. But would be nice to know on what it's used. 

Also I'm lost with depth and intensity. 

Some nice explanation like you already have on the readme with images would be appreciated ^^

**Comment by florent37** [comment]
I'll close it when I will publish the 3.0.0 :)

**Comment by florent37** [comment]
close it because moved to #135
