### ISSUE TITLE
NeumorphicRadioStyle/NeumorphicCheckboxStyle lightSource

### ISSUE THREAD

**Issue by jaumard** [Idean/Flutter-Neumorphic#131]
Any reason we don't have lightSource on radio/check button ?

**Comment by jaumard** [comment]
If not they can use directly the NeumorphicStyle and not have a specific style just for them

**Comment by florent37** [comment]
maybe we forgot to add this

**Comment by florent37** [comment]
I just added this as MR

**Comment by florent37** [comment]
merged, I have some small things to change before I publish it (I'll move shape into style before)

I want to publish a 2.5.0 or 3.0.0 (with official text support)

**Comment by florent37** [comment]
and your work :) on app

I will have to rework the readme too to explain how each component of style work (intensity, surface intensity etc.) & create assoricated gifs
