### ISSUE TITLE
Light from above ?

### ISSUE THREAD

**Issue by jaumard** [Idean/Flutter-Neumorphic#132]
Sorry if it's a dumb question but why not having a light from above ?

**Comment by florent37** [comment]
above ? like everything is white ?

**Comment by jaumard** [comment]
hum more black no ?

**Comment by florent37** [comment]
Maybe :) but no it's not implemented we only implemented light from a side

**Comment by florent37** [comment]
I don't know it it's usefull to implement this :/

**Comment by florent37** [comment]
I close if for now, it's not really useful for neumorphic, and it breaks all the maths inside decorations 😅
