### ISSUE TITLE
Publish the 3.0.0

### ISSUE THREAD

**Issue by florent37** [Idean/Flutter-Neumorphic#135]
- [x] Add neumorphicApp & NeumorphicToolbar
- [x] Move BoxShape into style / theme
- [x] Add NeumorphicText
- [x] Add NeumorphicIcon
- [x] Add tooltip (accessibility)
- [x]  Into readme explain depth/intensity/surfaceIntensity
- [x]  export some material widgets from neumorphic package (text, datepicker etc.)
- [x] explain how text work in readme
- [x] explain how icon / svg work in readme
- [x] Add NeumorphicApp explanation on README
- [x] Add NeumorphicFloatingButton
- [x] Add Contributors
- [x] update the changelog

**Comment by florent37** [comment]
@jaumard feel free to comment & add things here

**Comment by jaumard** [comment]
Just out of me mind, in theme we need a `buttonStyle` too, because if we use `boxShape` of the theme it will apply it to buttons but also all `Neumorphic` containers and we might want all my buttons as `circle` but I don't want it for my `Neumorphic` containers.

**Comment by florent37** [comment]
I updated the readme & checked some :)

**Comment by florent37** [comment]
NeumorphicFloatingButton -> I create an issue for this

**Comment by florent37** [comment]
published **insert a dancing gif here** 

https://pub.dev/packages/flutter_neumorphic

thanks everybody for your contributions !
