### ISSUE TITLE
NeumorphicButton isEnabled not natural to use

### ISSUE THREAD

**Issue by jaumard** [Idean/Flutter-Neumorphic#137]
I was searching how to have a disabled buttons ! And I had to check the example on how to do it, because naturally I did same as in material and settings `onPressed: null` but it didn't work ^^ and then I find there is a `isEnabled`.

Would be nice to use same convention as Cupertino/material and remove `isEnabled` on use the presence or not of `onPressed` callback

**Comment by florent37** [comment]
yes that make sense, I change it
