### ISSUE TITLE
NeumorphicApp or NeumorphicTheme

### ISSUE THREAD

**Issue by bartonhammond** [Idean/Flutter-Neumorphic#141]
Nice work, thanks for making this available.
I'm new w/ Dart & Flutter.  When I cloned the repo I looked at the example which uses 
```
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return NeumorphicApp(
```
But when I install `  flutter_neumorphic: ^2.2.2` and then look in the `flutter/.pub-cache/hosted/pub.dartlang.org/flutter_neumorphic-2.2.2/example/` it's a different example and has:
```
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: NeumorphicTheme(
```
Should I use the App or Theme version?  And if the App, how would I install that?

**Comment by florent37** [comment]
we're currently adding the NeumorphicApp, its why it's on master but not pushed on pub.dev

for now please use the NeumorphicTheme

in few days we'll publish the 3.0.0 which will include the neumorphic app & more :) 

you'll can update your project if you want !
