### ISSUE TITLE
NeumorphicFloatingButton

### ISSUE THREAD

**Issue by florent37** [Idean/Flutter-Neumorphic#142]
@jaumard can you do this please :) ? 
or describe this for me to do this

I think it's for the Scaffold

**Comment by florent37** [comment]
floatingActionButton: NeumorphicFloatingActionButton(
        child: Icon(Icons.add, color: NeumorphicTheme.accentColor(context), size: 30),
        onPressed: (){

        },
 ),

**Comment by jaumard** [comment]
Liked it :) we can imagine an IconTheme under the NeumorphicTheme, it will avoid the need of `NeumorphicTheme.accentColor(context) ` everywhere and will be used for all icons not only this widget

**Comment by florent37** [comment]
I think it can wait a 3.0.1 :)
