### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by ivanlunardi** [Idean/Flutter-Neumorphic#143]
I have  found a version mismatch:
on https://pub.dev/packages/flutter_neumorphic you can find 2.2.2 but when i try to get i receive the 2.2.1

**Comment by florent37** [comment]
we will publish 3.0.0 in few days, until please use 2.2.1 :)

**Comment by florent37** [comment]
https://github.com/Idean/Flutter-Neumorphic/issues/135
