### ISSUE TITLE
NeumorphicStyle, boxShape isn't defined in the scope

### ISSUE THREAD

**Issue by Sammy-iiitb** [Idean/Flutter-Neumorphic#144]
```
Neumorphic(
            style: NeumorphicStyle(
              shape: NeumorphicShape.concave,
              boxShape: NeumorphicBoxShape.roundRect(BorderRadius.circular(12),),
              depth: 8,
              lightSource: LightSource.topLeft,
              color: Colors.grey,)
        ),
```
boxShape is not a parameter in NeumorphicStyle, is there any other way to import it.

**Comment by Sammy-iiitb** [comment]
boxShape should come under Neumorphic widget and not under NeumorphicStyle widget.

**Comment by florent37** [comment]
yes it's because we're moving to a 3.0.0 of the library, and it'll be in style 

for now (2.0.0) it's inside the widget

we should do this inside a different branch but it's not master, sorry

**Comment by florent37** [comment]
in few days in 3.*.*  the boxshape will be in style

**Comment by Sammy-iiitb** [comment]
Thanks

**Comment by florent37** [comment]
It's published
