### ISSUE TITLE
NeumorphicSlider ignores gestures under certain conditions

### ISSUE THREAD

**Issue by MrHarcombe** [Idean/Flutter-Neumorphic#155]
We have an app using your Neumorphic theme (love it, thanks) but we're trying to use the NeumorphicSlider and have hit a point where it isn't detecting gestures from the user when it is below a gesture detector, inside of a stack. The normal material slider is able to work and update, however the Neumorphic one doesn't respond reliably (if at all). 

Any thoughts?

**Comment by RaminNikmanesh** [comment]
Same problem

**Comment by RaminNikmanesh** [comment]
are u sure use setState function?
