### ISSUE TITLE
NeumorphicButton throws error with version flutter_neumorphic 3.0.1

### ISSUE THREAD

**Issue by msarkrish** [Idean/Flutter-Neumorphic#158]
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building _BodyBuilder:
The getter 'current' was called on null.
Receiver: null
Tried calling: current

The relevant error-causing widget was: 
  Scaffold file:///home/krishnakumar/Flutter_Projects/dhwark/lib/screens/home_screen.dart:34:12
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _NeumorphicButtonState.updateInitialStyle (package:flutter_neumorphic/src/widget/button.dart:95:49)
#2      _NeumorphicButtonState.didChangeDependencies (package:flutter_neumorphic/src/widget/button.dart:110:5)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4661:12)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (10924): Another exception was thrown: NoSuchMethodError: The getter 'current' was called on null.
I/flutter (10924): Another exception was thrown: Each child must be laid out exactly once.
I/flutter (10924): Another exception was thrown: NoSuchMethodError: The getter 'current' was called on null.
I/flutter (10924): Another exception was thrown: Each child must be laid out exactly once.
I/flutter (10924): Another exception was thrown: NoSuchMethodError: The getter 'current' was called on null.
I/flutter (10924): Another exception was thrown: Each child must be laid out exactly once.
I/flutter (10924): Another exception was thrown: NoSuchMethodError: The getter 'current' was called on null.
I/flutter (10924): Another exception was thrown: Each child must be laid out exactly once.
I/flutter (10924): Another exception was thrown: NoSuchMethodError: The getter 'current' was called on null.
I/flutter (10924): Another exception was thrown: Each child must be laid out exactly once.
I/flutter (10924): Another exception was thrown: NoSuchMethodError: The getter 'current' was called on null.
I/flutter (10924): Another exception was thrown: Each child must be laid out exactly once.

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
Each child must be laid out exactly once.
The relevant error-causing widget was: 
  Scaffold file:///home/krishnakumar/Flutter_Projects/dhwark/lib/screens/home_screen.dart:34:12
I/flutter (10924): Another exception was thrown: NoSuchMethodError: The getter 'current' was called on null.
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (10924): Another exception was thrown: Each child must be laid out exactly once.

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building _BodyBuilder:
The getter 'current' was called on null.
Receiver: null
Tried calling: current

The relevant error-causing widget was: 
  Scaffold file:///home/krishnakumar/Flutter_Projects/dhwark/lib/screens/home_screen.dart:34:12
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _NeumorphicButtonState.updateInitialStyle (package:flutter_neumorphic/src/widget/button.dart:95:49)
#2      _NeumorphicButtonState.didChangeDependencies (package:flutter_neumorphic/src/widget/button.dart:110:5)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4661:12)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (10924): Another exception was thrown: NoSuchMethodError: The getter 'current' was called on null.
I/flutter (10924): Another exception was thrown: Each child must be laid out exactly once.
I/flutter (10924): Another exception was thrown: NoSuchMethodError: The getter 'current' was called on null.
I/flutter (10924): Another exception was thrown: Each child must be laid out exactly once.
I/flutter (10924): Another exception was thrown: NoSuchMethodError: The getter 'current' was called on null.
I/flutter (10924): Another exception was thrown: Each child must be laid out exactly once.
I/flutter (10924): Another exception was thrown: NoSuchMethodError: The getter 'current' was called on null.
I/flutter (10924): Another exception was thrown: Each child must be laid out exactly once.
I/flutter (10924): Another exception was thrown: NoSuchMethodError: The getter 'current' was called on null.
I/flutter (10924): Another exception was thrown: Each child must be laid out exactly once.
I/flutter (10924): Another exception was thrown: NoSuchMethodError: The getter 'current' was called on null.
I/flutter (10924): Another exception was thrown: Each child must be laid out exactly once.

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
Each child must be laid out exactly once.
The relevant error-causing widget was: 
  Scaffold file:///home/krishnakumar/Flutter_Projects/dhwark/lib/screens/home_screen.dart:34:12
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (10924): Another exception was thrown: NoSuchMethodError: The getter 'current' was called on null.
I/flutter (10924): Another exception was thrown: Each child must be laid out exactly once.

**Comment by edex96** [comment]
Same here

`══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building DefaultTextStyle(debugLabel: ((((englishLike
body1 2014).merge(blackMountainView bodyText2)).apply).copyWith).copyWith, inherit: false, color:
Color(0xff40494f), family: Signika_regular, familyFallback: [Signika], size: 14.0, weight: 400,
baseline: alphabetic, decoration: TextDecoration.none, softWrap: wrapping at box width, overflow:
clip):
The getter 'current' was called on null.
Receiver: null
Tried calling: current
The relevant error-causing widget was:
  Material
  
lib\widgets\GamesAction.dart:25
When the exception was thrown, this was the stack:
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)
#1      _NeumorphicButtonState.updateInitialStyle  (package:flutter_neumorphic/src/widget/button.dart:95:49)
#2      _NeumorphicButtonState.didChangeDependencies  (package:flutter_neumorphic/src/widget/button.dart:110:5)`

**Comment by BossSuricate** [comment]
The same for me

`════════ Exception caught by widgets library ═══════════════════════════════════
The following NoSuchMethodError was thrown building Container(center, bg: BoxDecoration(color: Color(0xffffffff), borderRadius: BorderRadius.circular(20.0)), constraints: BoxConstraints(w=350.0, h=350.0)):
The getter 'current' was called on null.
Receiver: null
Tried calling: current

The relevant error-causing widget was
    Container 
lib/…/home/home.dart:14
When the exception was thrown, this was the stack
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
#1      _NeumorphicButtonState.updateInitialStyle 
package:flutter_neumorphic/…/widget/button.dart:95
#2      _NeumorphicButtonState.didChangeDependencies 
package:flutter_neumorphic/…/widget/button.dart:110
#3      StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:4661
#4      ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4476
...
════════════════════════════════════════════════════════════════════════════════`

**Comment by guit4eva** [comment]
+1

**Comment by eliraudcoel** [comment]
The same for me... ;)
+1

**Comment by Sully55** [comment]
Same

**Comment by shelarsuhas** [comment]
+1
