### ISSUE TITLE
ThemeData and the NeumorphicThemeData

### ISSUE THREAD

**Issue by yusoofsh** [Idean/Flutter-Neumorphic#163]
There's this new official package [animations](https://pub.dev/packages/animations).
How to use the `pageTransitionsTheme` on `ThemeData` properties in NeumorphicThemeData?
Here's a quick snippets:
```dart
void main() {
  runApp(
    MaterialApp(
      theme: ThemeData.from(
        colorScheme: const ColorScheme.light(),
      ).copyWith(
        pageTransitionsTheme: const PageTransitionsTheme(
          builders: <TargetPlatform, PageTransitionsBuilder>{
            TargetPlatform.android: ZoomPageTransitionsBuilder(),
          },
        ),
      ),
      home: _TransitionsHomePage(),
    ),
  );
}
```

**Comment by amoslai5128** [comment]
Same here!

**Comment by zkx2020** [comment]
same here! I want to use ThemeData(
            splashColor:Colors.transparent,
            highlightColor: Colors.transparent,
          ),but how??
