### ISSUE TITLE
The getter 'current' was called on null.

### ISSUE THREAD

**Issue by Sully55** [Idean/Flutter-Neumorphic#165]
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           28.9s
Waiting for iPhone 11 Pro Max to report its views...
Debug service listening on ws://127.0.0.1:64802/Q67mBkethH4=/ws
Syncing files to device iPhone 11 Pro Max...

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building Buttons:
The getter 'current' was called on null.
Receiver: null
Tried calling: current

The relevant error-causing widget was:
  Buttons

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _NeumorphicButtonState.updateInitialStyle (package:flutter_neumorphic/src/widget/button.dart:95:49)
#2      _NeumorphicButtonState.didChangeDependencies (package:flutter_neumorphic/src/widget/button.dart:110:5)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4705:12)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
...     Normal element mounting (25 frames)
#29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#30     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991:32)
...     Normal element mounting (94 frames)
#124    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#125    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991:32)
...     Normal element mounting (136 frames)
#261    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#262    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991:32)
...     Normal element mounting (258 frames)
#520    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#521    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#522    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1174:16)
#523    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1145:5)
#524    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1087:17)
#525    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:19)
#526    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1086:13)
#527    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:927:7)
#528    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:908:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building Buttons:
The getter 'current' was called on null.
Receiver: null
Tried calling: current

The relevant error-causing widget was: 
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _NeumorphicButtonState.updateInitialStyle (package:flutter_neumorphic/src/widget/button.dart:95:49)
#2      _NeumorphicButtonState.didChangeDependencies (package:flutter_neumorphic/src/widget/button.dart:110:5)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4705:12)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port

**Comment by leidig54** [comment]
What was the solution here?

**Comment by FelipeMarra** [comment]
> What was the solution here?

Yeah, kind of passing through the same problem right now

**Comment by hiwa-jalal** [comment]
we need a solution for this, why just close it!

**Comment by leidig54** [comment]
I’m my case I just needed to wrap the widget it Nuemorphic theme

**Comment by hiwa-jalal** [comment]
@leidig54 yes that work, but i think it's still better to be able to just use it.
