### ISSUE TITLE
Dark Themed Apps

### ISSUE THREAD

**Issue by m-j-g** [Idean/Flutter-Neumorphic#179]
Hey Guys, nice work on the library, looks really nice.  The white feels really good.  The dark doesn't look/feel believable though, right?  I've included some screenshots to compare.

<img width="360" alt="Screen Shot 2020-10-05 at 8 20 28 AM" src="https://user-images.githubusercontent.com/10711395/95084679-d244d000-06e3-11eb-82b9-d5ce60c3d288.png">

<img width="527" alt="Screen Shot 2020-10-05 at 8 22 24 AM" src="https://user-images.githubusercontent.com/10711395/95085208-8181a700-06e4-11eb-9b06-171f528f6d04.png">
<img width="688" alt="Screen Shot 2020-10-05 at 8 22 33 AM" src="https://user-images.githubusercontent.com/10711395/95085225-86def180-06e4-11eb-896a-de84cefc2421.png">

<img width="541" alt="Screen Shot 2020-10-05 at 8 22 59 AM" src="https://user-images.githubusercontent.com/10711395/95085222-847c9780-06e4-11eb-8e54-312fc151e7e1.png">

**Comment by florent37** [comment]
it's just because I used flat buttons on the sample, you can use concave / convex to feel the same ui :) look at others samples in the app

**Comment by m-j-g** [comment]
@florent37 Thanks for the response and your work!  I was referring to the shadowing, but I take it that this is appearing as intended so no worries.
