### ISSUE TITLE
Add Get (aka GetX) support

### ISSUE THREAD

**Issue by subzero911** [Idean/Flutter-Neumorphic#183]
I want to use https://pub.dev/packages/get
It's a modern all-in-one architecture, easy to use.
The problem is that it is necessary to make GetMaterialApp a root widget instead of MaterialApp.
But your package requires to make NeumorphicApp a root widget. So I cannot use both simultaneously. 
I asked Get authors to add Neumorphic support, but they denied my request: https://github.com/jonataslaw/getx/issues/723
So I ask you to add an ability to use Get.

**Comment by israelhudson** [comment]
i have the same problem

**Comment by batnhau** [comment]
Same here.

**Comment by hk7math** [comment]
I tried wrapping like this, and it seems working as expected for displaying dialogs

from a Flutter newbie 
```
Widget build(BuildContext context) {
    return GetMaterialApp(
        home: NeumorphicApp(
        ....
```

**Comment by IbneUmmah** [comment]
It does work but just for only one screen not as a whole app and messes with dark mode.

**Comment by miguelpruivo** [comment]
Mixing 3rd party libraries shouldn't be done, specially when they enforce other plugin users to depend on it even if not needed.

I suggest you to use @hk7math solution if you want to use it along with GetX.
