### ISSUE TITLE
Flutter_Neumorphic Not working with flutter version 2.5.2

### ISSUE THREAD

**Issue by shaikhafzaa2** [Idean/Flutter-Neumorphic#241]
PS C:\Users\Dell G3-3500\Desktop\Internship Grow90\edu_app> flutter run
Using hardware rendering with device sdk gphone x86 arm. If you notice graphics artifacts, consider
enabling software rendering with "--enable-software-rendering".
Launching lib\main.dart on sdk gphone x86 arm in debug mode...
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_neumorphic-3.1.0/lib/src/widget/button.dart:200:14: Error: 'AnimatedScale' is imported from both 'package:flutter/src/widgets/implicit_animations.dart' and 'package:flutter_neumorphic/src/widget/animation/animated_scale.dart'.
      child: AnimatedScale(
             ^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_neumorphic-3.1.0/lib/src/widget/switch.dart:167: 'package:flutter_neumorphic/src/widget/animation/animated_scale.dart'.
            child: AnimatedScale(
                   ^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1005

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 58s

**Comment by pratikbaid3** [comment]
I am having the same issue

**Comment by shaikhafzaa2** [comment]
> I am having the same issue

For now I have just downgraded my flutter version to 2.2.3 and its working Its not a solution tho

**Comment by darshansatra1** [comment]
[https://github.com/Idean/Flutter-Neumorphic/issues/239#issuecomment-931642207](https://github.com/Idean/Flutter-Neumorphic/issues/239#issuecomment-931642207) refer to this comment, I did this and it worked. Although it's not a good solution to go tinkering with the package code but for now we have no other option.

**Comment by rohitrvayuz** [comment]
same error after flutter upgrade to 2.5.2

**Comment by Makarov96** [comment]
Metanle nitro papis

**Comment by ajaygosh102** [comment]
I am having the same issue

**Comment by miguelpruivo** [comment]
This should be working on the latest published version (3.1.1) could you please give it a try?

**Comment by miguelpruivo** [comment]
This should be already fixed in the latest version. Let me know if you experience any issue. Thank you!

**Comment by ramyagokulp** [comment]
I'm having the same issue with 3.10.6. which is the current latest version of Flutter SDK till July 2023.

**Comment by chaiebmohamed** [comment]
> I'm having the same issue with 3.10.6. which is the current latest version of Flutter SDK till July 2023.

did u found any solution ?
