### ISSUE TITLE
Flutter_Neumorphic Not working with flutter version 2.5.1,2.5.2,2.5.3

### ISSUE THREAD

**Issue by weddingstudio007** [Idean/Flutter-Neumorphic#242]
/M:/flutter_sdks/flutter_windows_2.5.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_neumorphic-3.1.0/lib/src/widget/button.dart:200:14: Error: 'AnimatedScale' is imported from both 'package:flutter/src/widgets/implicit_animations.dart' and 'package:flutter_neumorphic/src/widget/animation/animated_scale.dart'.
      child: AnimatedScale(
             ^^^^^^^^^^^^^
/M:/flutter_sdks/flutter_windows_2.5.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_neumorphic-3.1.0/lib/src/widget/switch.dart:167:20: Error: 'AnimatedScale' is imported from both 'package:flutter/src/widgets/implicit_animations.dart' and 'package:flutter_neumorphic/src/widget/animation/animated_scale.dart'.
            child: AnimatedScale(
                   ^^^^^^^^^^^^^

/M:/flutter_sdks/flutter_windows_2.5.3-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_neumorphic-3.1.0/lib/src/widget/button.dart:200:14: Error: 'AnimatedScale' is imported from both 'package:flutter/src/widgets/implicit_animations.dart' and 'package:flutter_neumorphic/src/widget/animation/animated_scale.dart'.
      child: AnimatedScale(
             ^^^^^^^^^^^^^
/M:/flutter_sdks/flutter_windows_2.5.3-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_neumorphic-3.1.0/lib/src/widget/switch.dart:167:20: Error: 'AnimatedScale' is imported from both 'package:flutter/src/widgets/implicit_animations.dart' and 'package:flutter_neumorphic/src/widget/animation/animated_scale.dart'.
            child: AnimatedScale(
                   ^^^^^^^^^^^^^
Please fix ..and give new update

**Comment by rednikisfun** [comment]
Why is this issue closed, is it fixed? I have encountered the same problem

**Comment by weddingstudio007** [comment]
Because. I solved it

**Comment by d3fkon** [comment]
How did you solve it? Can you please share the fix

**Comment by weddingstudio007** [comment]
flutter_neumorphic:
    git:
      url: https://github.com/tsvillain/Flutter-Neumorphic.git
please add this line in your pubspec.yaml
