### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by mjablecnik** [Idean/Flutter-Neumorphic#244]
@kcrebound @meltenc @cadicetienne @imp-dance @jaumard 
Is this project dead? Because I don't see very big activity here for last year and a lot of PR or Issues are not resolving..

**Comment by miguelpruivo** [comment]
Looks like maintainers are missing. Maybe you may want to give someone access to at least handle the PRs and help you out with it. I don't mind helping if you want.

**Comment by florent37** [comment]
Hi yes sorry we do not have time to maintain it, @miguelpruivo I gave you maintain rights if you want to make it alive with adding others maintainers etc,  we'll be so grateful

**Comment by miguelpruivo** [comment]
@florent37 no problem. I’ll see what I can do, at least I should be able to review/check critical PRs, however I won’t probably be able to publish on pub.dev unless you invite me there as well (miguelruivo.com).

**Comment by florent37** [comment]
Yes you can already do it with the job 💪

**Comment by miguelpruivo** [comment]
> Yes you can already do it with the job 💪

Great!

Closing.
