### ISSUE TITLE
Null Check on a null Value NeumorphicAppBar

### ISSUE THREAD

**Issue by rennylangat** [Idean/Flutter-Neumorphic#249]
- Upon following this error? I discovered it is thrown by checking if theme has been set Line 238
`
centerMiddle:
                    widget._getEffectiveCenterTitle(theme, nTheme!.current!),
                middleSpacing: widget.titleSpacing,
`

- By default an AppBar should just return a sort of container with blue background and a leading icon of Arrow Back.

**Comment by jabirmayar** [comment]
any update on this?

**Comment by Abhith** [comment]
I was able to get around this issue by wrapping the page content in a `NeumorphicTheme` widget as in the example below,

```dart
class _FirstThemeWidgetPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return NeumorphicTheme(
      themeMode: ThemeMode.light,
      theme: NeumorphicThemeData(
        lightSource: LightSource.topLeft,
        accentColor: NeumorphicColors.accent,
        appBarTheme: NeumorphicAppBarThemeData(
          buttonStyle: NeumorphicStyle(boxShape: NeumorphicBoxShape.circle()),
          textStyle: TextStyle(color: Colors.black54),
          iconTheme: IconThemeData(color: Colors.black54, size: 30),
        ),
        depth: 4,
        intensity: 0.9,
      ),
      child: AppBarPageUsingTheme(),
    );
  }
}
```

**Comment by rennylangat** [comment]
@Abhith Thanks for the work around. Probably create a PR for the same?
