### ISSUE TITLE
Error After Updating Xcode and Flutter

### ISSUE THREAD

**Issue by imdewan** [Idean/Flutter-Neumorphic#278]
It wasn't there but started showing after updating, sometimes it says accentColor isn't defined

`Error (Xcode): ../../../.pub-cache/hosted/pub.dev/flutter_neumorphic-3.2.0/lib/src/widget/app_bar.dart:183:29: Error: The getter 'textTheme' isn't defined for the class 'AppBarTheme'.`

**Comment by benji-farquhar** [comment]
Add[ this to your pubspec.yaml](https://github.com/Idean/Flutter-Neumorphic/issues/274#issuecomment-1546513799)

**Comment by imdewan** [comment]
thanks

> Add[ this to your pubspec.yaml](https://github.com/Idean/Flutter-Neumorphic/issues/274#issuecomment-1546513799)
