### ISSUE TITLE
TODO : Circular progress

### ISSUE THREAD

**Issue by florent37** [Idean/Flutter-Neumorphic#36]
<img width="781" alt="Capture d’écran 2020-02-26 à 11 08 22" src="https://user-images.githubusercontent.com/5754972/75334545-5995af80-5888-11ea-9e59-6e218ea3fe77.png">

not necessary this design

**Comment by florent37** [comment]
will be done on demand, if someone need this

**Comment by miguelpruivo** [comment]
@florent37 has this been implemented? I need something similar to `CircularProgressBar` with Neumorphic style. Something like this:
<img width="65" alt="Captura de ecrã 2021-02-16, às 17 36 51" src="https://user-images.githubusercontent.com/27860743/108100234-8e90a880-707d-11eb-80cc-b7325e653c2a.png">
