### ISSUE TITLE
Tap effect flickering when Theme changes

### ISSUE THREAD

**Issue by giovannilattanzio** [Idean/Flutter-Neumorphic#60]
When you change any parameter with `NeumorphicTheme.of(context)` (e.g. the onClick function of the Audio Player Sample, or the Color Picker in the Container section), we have this wierd effect:

![theme-bug](https://user-images.githubusercontent.com/48157603/75999741-f993ae80-5f02-11ea-9dc7-25ab639f3438.gif)
(every flickering is a click, it's not doing it by itselft!)

It seems the old theme/color stays for a while, but after some times, the right effect is back on track

**Comment by florent37** [comment]
thanks I already saw this, but can't find where to fix it

I was thinking about exposing the theme to child widgets using a Stream

class AnyChildWidget ...

      build(context) {
            return StreamBuilder(
                    stream: NeumorphicTheme.of(context).themeStream,
                    builder: (context, snap){
                            //build the widget using the fresh theme
                    } 
            )

**Comment by florent37** [comment]
fixed in https://github.com/Idean/Flutter-Neumorphic/pull/61,
will be available on next release :) thanks for the report !
