### ISSUE TITLE
Add a break in change label when renaming varibales

### ISSUE THREAD

**Issue by hmlafrugalitas** [Idean/Flutter-Neumorphic#62]
In the last version 1.0.1, some variables was renamed causing a break in the existing code.

- Renamed CurrentTheme to UsedTheme in NeumorphicTheme (Dark, Light, System)
- Renamed NeumorphicTheme.getCurrentTheme(context) to NeumorphicTheme.currentTheme(context)

Can you please add a tag for such change so when we read the change log we can detect them.

Thanks.

**Comment by florent37** [comment]
Ok I will add the 1.0.1

Le dim. 8 mars 2020 à 12:36, hmlafrugalitas <notifications@github.com> a
écrit :

**Comment by florent37** [comment]
BTW it's in the changelog.md

Le dim. 8 mars 2020 à 12:36, hmlafrugalitas <notifications@github.com> a
écrit :

**Comment by florent37** [comment]
done : https://github.com/Idean/Flutter-Neumorphic/releases/tag/1.0.1
