### ISSUE TITLE
[ NeumorphicButton ] Graphic bug when switching from portrait to landscape

### ISSUE THREAD

**Issue by tperraut** [Idean/Flutter-Neumorphic#65]
First of all, thank you for your work !

When I switch from portrait to landscape or from landscape to portrait, the button does not rebuild as expected until I click on it. Here are some screenshots :
- In portrait : https://imgur.com/7Vo6Yfu
- After switching from portrait to landscape : https://imgur.com/k5e6Ohg
- After clicking on the first button in landscape : https://imgur.com/kK6jeZi

The behavior is the same if I start from landscape and switch to portrait, buttons are not rebuild correctly. But if I do : 
- portrait -> landscape -> portrait, without clicking, in portrait button looks as expected
- landscape -> portrait -> landscape, without clicking, in landscape button looks as expected

This bug also happens in both platforms.

I stay around if you need more infos !

**Comment by tperraut** [comment]
Seems related to #32 , sorry for inconvenience :)

**Comment by florent37** [comment]
it's not the same as #32, it's a new issue :) 
thanks for the report ! 
will work on it

**Comment by giovannilattanzio** [comment]
Same issue when you are in a Scrollable View (SingleChildScrollView for example) and the screen moves up and down because of the keyboard is showing: if you put down the keyboard and the screen comes back to the starting point, button is not rebuilt correctly.

If you press it, it comes back ok

**Comment by florent37** [comment]
I fixed it in last commit, before I send a new version I want to finish the new samples / widgets pages, so it will be available in few days, thanks for the report, will publish a new version soon :)

**Comment by florent37** [comment]
will be part of 1.0.2
