### ISSUE TITLE
Disabled depth

### ISSUE THREAD

**Issue by giovannilattanzio** [Idean/Flutter-Neumorphic#77]
I thought it could be cool to have an optional disabled/not enabled depth, rather than always 0 as of right now (in `NeumorphicButton` expecially).

I'd done it myself, but one question came in my mind: could a **disabledDepth** in `NeumorphicStyle` be the right way to do it?
And should it affect all components (which ones?), or `NeumorphicButton` only (in this case, an inner variable in this class could be better)?

p.s. Thanks for the great package: it becomes better and better every release comes up!

**Comment by florent37** [comment]
you want to disable the depth of only one widget ?

```
NeumorphicButton(
     disableDepth: true
     ...
)
```

or all widgets of the current page ?

```
NeumorphicTheme(
     theme: NeumorphicThemeData(
             disableDepth: true
    )
    child: ...
)
```

**Comment by giovannilattanzio** [comment]
As of right now, I build two widget (one with `depth: 10`, for example, when is enabled, and one with `depth: 3` when is disabled, but I realize this is not the ideal way to proceed.

I want to replicate the **depth** logic with a new parameter **disableDepth** (`double` like the previous) and modify this

  ```
double _getDepth() {
    if (widget.isEnabled) {
      return this.depth;
    } else {
      return 0;
    }
  }
```

with something like this

  ```
double _getDepth() {
    if (widget.isEnabled) {
      return this.depth;
    } else {
      return this.disabledDepth ?? 0;
    }
  }
```
(or have better getter and setter, for higher elegancy)

So maybe both situations are good: we need a Theme level disabledDepth and a Style level disabledDepth. When latter is null, we should take the Theme one (as it does right now with the `depth` value) 

I thought it should involve Buttons, Radio, Checkbox, but I don't know if other components have to look over it

**Comment by florent37** [comment]
added in theme & each style

```
theme: NeumorphicThemeData(
             disableDepth: true
    )
```

& 

```
style: Neumorphic{ELEMENT}Style(
             disableDepth: true
    )
```

**Comment by florent37** [comment]
I publish a 1.0.3 with this 👍

**Comment by giovannilattanzio** [comment]
Great!

Buuut (😆) with this change, the depth value is still 0 if we set disableDepth to true.
What I was thinking is to declare this parameter as a double and to use it as height for the disabled (isEnabled: false) button/radio/checkbox, whereas 0 can remain the default value if this new one is not setted.

That's why I was thinking in something like this:

```
double _getDepth() {
  if (widget.isEnabled) {
    return this.depth;
  } else {
    return this.disabledDepth ?? 0;
  }
}
```

Maybe it could be the next enhancement!
