### ISSUE TITLE
Shadow bad rendering

### ISSUE THREAD

**Issue by QuentinSc** [Idean/Flutter-Neumorphic#80]
Hello and thank you for your awesome work!

Just tried your package and I have an issue on web, shadow seems to be cropped.
I made a compare between your sample hosted on my computer and your sample hosted on firebase. (Flutter 1.15.17)

You can see that bottom and right side are cropped :/

![image](https://user-images.githubusercontent.com/16439299/77479887-f401f800-6e20-11ea-9f44-438544279e14.png)

![image](https://user-images.githubusercontent.com/16439299/77479965-18f66b00-6e21-11ea-89df-6559ee012b96.png)

Did I miss something ?

Thank you !

**Comment by florent37** [comment]
I'm currently using flutter (Channel master, v1.16.3-pre.7, on Mac OS X 10.14.5 18F132, locale
    fr-FR)

Flutter web is still a "preview" so I just shipped this online version but every flutter update it can change radically and may now work, try to "exclude" flutter for web for now if you can :/ 

or if you find a working version, keep it ! 😄 

btf can you try the master 1.16.3 please ?

**Comment by QuentinSc** [comment]
Yes I'm agree with you. I wanted my new app the more "web ready" possible ^^" but I will wait 
On master (v1.16.3-pre.30) it's okay :)
Thank you and I will close this 
(can't wait for your next releases !)
