### ISSUE TITLE
Slider colour leak at extremes

### ISSUE THREAD

**Issue by georgeherby** [Idean/Flutter-Neumorphic#86]
When I use the Slider widget it looks visually find unless I slide it to the extremes on the right and left

In the middle - no issue
![image](https://user-images.githubusercontent.com/21989833/78183154-58dfd280-745f-11ea-80f0-76c76539f2c5.png)

When at the left extreme
![Screenshot 2020-04-01 at 21 24 22](https://user-images.githubusercontent.com/21989833/78183224-71e88380-745f-11ea-9daa-0c2e0cf4f884.png)

When at the right extreme
![Screenshot 2020-04-01 at 21 24 31](https://user-images.githubusercontent.com/21989833/78183314-9b091400-745f-11ea-8d43-a8ce442f1a6f.png)

Happy to provide some code for this if needed :)
 
I am running beta, v1.15.17 and on iPhone simulator

**Comment by florent37** [comment]
I reproduced it too, will be fixed soon :) thanks for the issue !
