### ISSUE TITLE
[1.0.3+1] Button box shape radius not correctly rendering

### ISSUE THREAD

**Issue by hmlafrugalitas** [Idean/Flutter-Neumorphic#87]
If we specify a custom boxshape radius, this one is not correctly applied.

`NeumorphicButton(
              padding: EdgeInsets.all(8),
              onClick: () {

              },
              style: NeumorphicStyle(
                shape: NeumorphicShape.concave,
                depth: 5,
              ),
              boxShape: NeumorphicBoxShape.roundRect(
                  borderRadius:
                      BorderRadius.only(bottomLeft: Radius.circular(12))
                  // BorderRadius.only(
                  //     topLeft: Radius.circular(12),
                  //     bottomLeft: Radius.circular(12),
                  //     topRight: Radius.circular(0),
                  //     bottomRight: Radius.circular(0))
                  ),
              child: Icon(
                Icons.stop,
              ),
            ),`

If we set the top left corner, this one is applied for all the borders. 
if we set other corner, the button is rendered as a rectangle.

The idea is to be able to create a grouped button options.

**Comment by florent37** [comment]
<img width="224" alt="Capture d’écran 2020-04-04 à 23 06 58" src="https://user-images.githubusercontent.com/5754972/78461435-276a3f80-76c9-11ea-83fd-55959674e2c7.png">

**Comment by florent37** [comment]
fixed, will be in 1.0.4 ! (just publishing it)

**Comment by florent37** [comment]
thanks for the issue !
