### ISSUE TITLE
Its possible to choose color ?

### ISSUE THREAD

**Issue by yacineblr** [Idean/Flutter-Neumorphic#89]
Hi, its possible to choose the color of the shadows? 
For example:
```
Neumorphic(
            style: NeumorphicStyle(
              firstColor: Colors.white, <----
              secondColor: Colors.black, <----
            ),
            boxShape: NeumorphicBoxShape.circle(), 
            child: Icon(Icons.star_border, size: 17, color: Theme.of(context).accentColor)
)
```

**Comment by florent37** [comment]
Shadows colors are fixed as white / dark on neumorphic ''guidelines'', btw I can make it mutable for your usecase, I'll make it today

**Comment by yacineblr** [comment]
I understand, it's because black doesn't appear enough, my background color is "Color.fromRGBO(39, 42, 46, 1)"

Model:
<img width="587" alt="Capture d’écran 2020-04-17 à 09 25 18" src="https://user-images.githubusercontent.com/18519670/79543348-96627380-808d-11ea-992b-38bf86c6b189.png">

Flutter app:
![Capture d’écran 2020-04-17 à 09 26 04](https://user-images.githubusercontent.com/18519670/79543389-a712e980-808d-11ea-8c33-b441a1df478a.png)

**Comment by florent37** [comment]
you can play with style.intensity for your case

**Comment by yacineblr** [comment]
You can only see "black" with an intensity of 1.
Only white is too "white", that's why I wanted to change the colors and add an opacity only to the white color

**Comment by florent37** [comment]
Done, in theme & style you have now 

```
const NeumorphicStyle({
    this.shape = _defaultShape,
    this.lightSource,
    this.color,
    this.shadowLightColor,
    this.shadowDarkColor,
    this.shadowLightColorEmboss,
    this.shadowDarkColorEmboss,
```

I just published a new release 1.0.5 with this, can you try ? 

just remember by default the intensity is on 0.5, and it's a percentage of the alpha applied to the shadow color,

if you set the color to #FF FFFFFF with the default opacity, the shadow color applied will be #99 FFFFFF

if you want your exact color set into style, use intensity = 1

**Comment by yacineblr** [comment]
Thank you very much really!
It works on an element with depth greater than 0, only the custom color is not taken under 0.
![Capture d’écran 2020-04-17 à 11 41 09](https://user-images.githubusercontent.com/18519670/79555764-61abe780-80a0-11ea-8d34-a5d971ee03db.png)

**Comment by florent37** [comment]
below 0 it's shadowLightColorEmboss

**Comment by florent37** [comment]
< 0 

<img width="235" alt="Capture d’écran 2020-04-17 à 11 47 01" src="https://user-images.githubusercontent.com/5754972/79556298-2bbb3300-80a1-11ea-9216-9e455ec2d39b.png">

> 0
<img width="273" alt="Capture d’écran 2020-04-17 à 11 46 57" src="https://user-images.githubusercontent.com/5754972/79556307-2eb62380-80a1-11ea-9e63-b43e41f235e6.png">

**Comment by yacineblr** [comment]
Sorry, I didn't understand, it's okay
 It works perfectly, thank you very much 🙏

**Comment by florent37** [comment]
;)
